# Generated by Django 4.2.6 on 2023-11-04 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0005_raceresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='rank',
        ),
    ]
